name       : perl-test-differences
version    : 0.64
release    : 1
source     :
    - https://cpan.metacpan.org/authors/id/D/DC/DCANTRELL/Test-Differences-0.64.tar.gz : 9f459dd9c2302a0a73e2f5528a0ce7d09d6766f073187ae2c69e603adf2eb276
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Test::Differences - Test strings and data structures and show differences if not ok
description: |
    Test::Differences - Test strings and data structures and show differences if not ok
builddeps  :
    - perl-capture-tiny
    - perl-module-build
    - perl-text-diff
rundeps    :
    - perl-capture-tiny
    - perl-text-diff
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
