name       : perl-test-differences
version    : '0.69'
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/D/DC/DCANTRELL/Test-Differences-0.69.tar.gz : 18f644fdd4a1fef93ef3f7f67df8e95b593d811899f34bcbbaba4d717222f58f
homepage   : https://metacpan.org/pod/Test::Differences
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Test::Differences - Test strings and data structures and show differences if not ok
description: |
    Test::Differences - Test strings and data structures and show differences if not ok. When the code you're testing returns multiple lines, records or data structures and they're just plain wrong, an equivalent to the Unix diff utility may be just what's needed.
builddeps  :
    - perl-capture-tiny
    - perl-module-build
    - perl-test-pod             # check
    - perl-test-pod-coverage    # check
    - perl-text-diff
rundeps    :
    - perl-capture-tiny
    - perl-text-diff
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
